name: job_timer
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  asuka: ^2.0.0+1
  validatorless: ^1.2.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  fl_chart: ^0.51.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.3
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  equatable: ^2.0.3
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  isar_generator: ^2.5.0
      

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca-Thin.ttf
    
    - family: JobTimerIcons
      fonts:
        - asset: assets/fonts/JobTimerIcons.ttf
